In [1]:
import numpy as np

# The numpy array

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a1.ndim

1

In [4]:
a1.shape

(3,)

In [5]:
a2 = np.array([[1,2,3],[3,4,5]])
a2

array([[1, 2, 3],
       [3, 4, 5]])

In [6]:
a2.ndim

2

In [7]:
a2.shape

(2, 3)

In [ ]:
a3 = np.array([1,2,3.3])

In [14]:
a3.ndim

1

In [9]:
a3.dtype

dtype('float64')

In [15]:
a3 = np.array([1,2,3.3], dtype=int)
a3

array([1, 2, 3])

In [16]:
a4 = np.array([ ['f','l','a','k','e'],['s','n','a','k','e'],['a','w','a','k','e'] ])
a4.shape

(3, 5)

In [17]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [19]:
np.linspace(0,100,3, endpoint=False)

array([  0.        ,  33.33333333,  66.66666667])

# Basic operatations with arrays

In [20]:
a = np.arange(12)

In [21]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
a.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [23]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

In [24]:
A*B    

array([[2, 0],
       [0, 4]])

In [25]:
a = np.array([11,22])
b = np.array([18,7,6])
c = np.array([1,3,5])
d = np.concatenate((a,b,c))
d

array([11, 22, 18,  7,  6,  1,  3,  5])

In [26]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Indexing

In [29]:
a = np.reshape(np.arange(12),(4,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
a[0,0]

0

In [31]:
a[3,0]

9

In [32]:
a[1:3,0]

array([3, 6])

In [33]:
a[:,2]

array([ 2,  5,  8, 11])

In [34]:
a[0:4:2,0]

array([0, 6])

In [35]:
a[0,0] = 5

In [36]:
a

array([[ 5,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
b = np.array([[11, 22],[33, 44],[55, 66]])

In [38]:
c = b.reshape((b.shape[0], b.shape[1], 1))

In [39]:
c.shape

(3, 2, 1)

# Slicing

In [40]:
a = np.arange(1,37).reshape(6,6)

In [41]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [42]:
a[:,1]

array([ 2,  8, 14, 20, 26, 32])

In [43]:
a[0:2,4:6]

array([[ 5,  6],
       [11, 12]])

In [44]:
a[5,4:]

array([35, 36])

In [46]:
a[2::2, ::2]

array([[13, 15, 17],
       [25, 27, 29]])

# Boolean masking

In [47]:
a = np.reshape(np.arange(12),(4,3))

In [48]:
a>8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True]], dtype=bool)

In [49]:
a[a>8] = 0 

In [50]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 0, 0]])

# Broadcasting

In [51]:
a = np.array([1,2,3])
a * 10

array([10, 20, 30])

In [52]:
np.array([ 1,  2,  3]) * np.array([10, 10, 10])

array([10, 20, 30])

In [53]:
a = np.array([[1], [2], [3], [4]])
b = np.array([10, 20, 30])

In [54]:
a + b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [55]:
a = np.array([[1,2,3],[4,5,6]]) 
b = np.array([[1,2],[8,10],[3,12]]) 

In [56]:
a.shape

(2, 3)

In [57]:
b.shape

(3, 2)

# Exercise: distance to origin

In [58]:
dist_to_origin = [0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391]

In [59]:
dist = np.array(dist_to_origin)

In [63]:
dist_T = dist.reshape(10,1)
dist_T

array([[   0],
       [1498],
       [1063],
       [1968],
       [1498],
       [1758],
       [1469],
       [1472],
       [2230],
       [2391]])

In [61]:
dist_matrix = np.abs(dist - dist_T)

In [62]:
dist_matrix

array([[   0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1063,  435,    0,  905,  435,  695,  406,  409, 1167, 1328],
       [1968,  470,  905,    0,  470,  210,  499,  496,  262,  423],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1758,  260,  695,  210,  260,    0,  289,  286,  472,  633],
       [1469,   29,  406,  499,   29,  289,    0,    3,  761,  922],
       [1472,   26,  409,  496,   26,  286,    3,    0,  758,  919],
       [2230,  732, 1167,  262,  732,  472,  761,  758,    0,  161],
       [2391,  893, 1328,  423,  893,  633,  922,  919,  161,    0]])

# Copies and views

In [64]:
a = np.arange(5)
a
# array([ 0,  1,  2,  3,  4])

array([0, 1, 2, 3, 4])

In [65]:
b = a # "a" and "b" are bound to the same array
b[0] = 5
a
# array([ 5,  1,  2,  3,  4])

array([5, 1, 2, 3, 4])

In [66]:
a = np.arange(10)
b = a[:2] # "b" is a narrower view of the array
b[0] = 10
a
# array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [67]:
a = np.arange(10)
b = a.copy()[:2] # "b" is bound to a new array i.e. a copy of "a"
b[0] = 10
a
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a = np.arange(12)
b = a.reshape(3, 4) # reshape() returns a view of the array, but with a new shape
b
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
b[0] = 10 # changes the underlying data of both "a" and "b"
a
# array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9, 10, 11])

array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
b
# array([[10, 10, 10, 10],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

array([[10, 10, 10, 10],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
x=np.array(11)
x.shape

()

In [72]:
x = np.array([[1],[2],[3],[4]])
x.ndim

2

In [73]:
x.shape

(4, 1)

In [76]:
y = np.array([1,'2',3])
y

array(['1', '2', '3'],
      dtype='<U21')

In [77]:
y.ndim

1

In [78]:
y.shape

(3,)

In [79]:
y[0]

'1'

In [87]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
b[2]= 999
a[1]
a

array([  1, 200,   3, 999,   5])

In [81]:
b = np.array([[11, 22],[33, 44],[55, 66]])
c = b.reshape((b.shape[0], b.shape[1], 1))
c.shape

(3, 2, 1)